# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Diseño Parcial II - Métodos NuméricosETYBzy.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-10, 0, 811, 571))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QSize(40, 16))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 270, 981, 281))
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet(u"")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.RS22 = QLineEdit(self.tab_3)
        self.RS22.setObjectName(u"RS22")
        self.RS22.setGeometry(QRect(600, 150, 51, 51))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.RS22.setFont(font1)
        self.RS22.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS22.setReadOnly(True)
        self.RS01 = QLineEdit(self.tab_3)
        self.RS01.setObjectName(u"RS01")
        self.RS01.setGeometry(QRect(540, 30, 51, 51))
        self.RS01.setFont(font1)
        self.RS01.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS01.setReadOnly(True)
        self.RS00 = QLineEdit(self.tab_3)
        self.RS00.setObjectName(u"RS00")
        self.RS00.setGeometry(QRect(480, 30, 51, 51))
        self.RS00.setFont(font1)
        self.RS00.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS00.setReadOnly(True)
        self.RS20 = QLineEdit(self.tab_3)
        self.RS20.setObjectName(u"RS20")
        self.RS20.setGeometry(QRect(480, 150, 51, 51))
        self.RS20.setFont(font1)
        self.RS20.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS20.setReadOnly(True)
        self.RS11 = QLineEdit(self.tab_3)
        self.RS11.setObjectName(u"RS11")
        self.RS11.setGeometry(QRect(540, 90, 51, 51))
        self.RS11.setFont(font1)
        self.RS11.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS11.setReadOnly(True)
        self.RS21 = QLineEdit(self.tab_3)
        self.RS21.setObjectName(u"RS21")
        self.RS21.setGeometry(QRect(540, 150, 51, 51))
        self.RS21.setFont(font1)
        self.RS21.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS21.setReadOnly(True)
        self.RS10 = QLineEdit(self.tab_3)
        self.RS10.setObjectName(u"RS10")
        self.RS10.setGeometry(QRect(480, 90, 51, 51))
        self.RS10.setFont(font1)
        self.RS10.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS10.setReadOnly(True)
        self.label_3 = QLabel(self.tab_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(340, 110, 131, 21))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.label_3.setFont(font2)
        self.RS12 = QLineEdit(self.tab_3)
        self.RS12.setObjectName(u"RS12")
        self.RS12.setGeometry(QRect(600, 90, 51, 51))
        self.RS12.setFont(font1)
        self.RS12.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS12.setReadOnly(True)
        self.RS02 = QLineEdit(self.tab_3)
        self.RS02.setObjectName(u"RS02")
        self.RS02.setGeometry(QRect(600, 30, 51, 51))
        self.RS02.setFont(font1)
        self.RS02.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RS02.setReadOnly(True)
        self.btnSuma = QPushButton(self.tab_3)
        self.btnSuma.setObjectName(u"btnSuma")
        self.btnSuma.setGeometry(QRect(120, 100, 141, 51))
        self.btnSuma.setFont(font2)
        self.btnSuma.setStyleSheet(u"background-color: rgb(141, 141, 141);")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.RR01 = QLineEdit(self.tab_4)
        self.RR01.setObjectName(u"RR01")
        self.RR01.setGeometry(QRect(540, 30, 51, 51))
        self.RR01.setFont(font1)
        self.RR01.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR01.setReadOnly(True)
        self.RR00 = QLineEdit(self.tab_4)
        self.RR00.setObjectName(u"RR00")
        self.RR00.setGeometry(QRect(480, 30, 51, 51))
        self.RR00.setFont(font1)
        self.RR00.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR00.setReadOnly(True)
        self.RR22 = QLineEdit(self.tab_4)
        self.RR22.setObjectName(u"RR22")
        self.RR22.setGeometry(QRect(600, 150, 51, 51))
        self.RR22.setFont(font1)
        self.RR22.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR22.setReadOnly(True)
        self.RR20 = QLineEdit(self.tab_4)
        self.RR20.setObjectName(u"RR20")
        self.RR20.setGeometry(QRect(480, 150, 51, 51))
        self.RR20.setFont(font1)
        self.RR20.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR20.setReadOnly(True)
        self.RR11 = QLineEdit(self.tab_4)
        self.RR11.setObjectName(u"RR11")
        self.RR11.setGeometry(QRect(540, 90, 51, 51))
        self.RR11.setFont(font1)
        self.RR11.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR11.setReadOnly(True)
        self.RR21 = QLineEdit(self.tab_4)
        self.RR21.setObjectName(u"RR21")
        self.RR21.setGeometry(QRect(540, 150, 51, 51))
        self.RR21.setFont(font1)
        self.RR21.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR21.setReadOnly(True)
        self.RR10 = QLineEdit(self.tab_4)
        self.RR10.setObjectName(u"RR10")
        self.RR10.setGeometry(QRect(480, 90, 51, 51))
        self.RR10.setFont(font1)
        self.RR10.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR10.setReadOnly(True)
        self.btnResta = QPushButton(self.tab_4)
        self.btnResta.setObjectName(u"btnResta")
        self.btnResta.setGeometry(QRect(120, 100, 141, 51))
        self.btnResta.setFont(font2)
        self.btnResta.setStyleSheet(u"background-color: rgb(141, 141, 141);")
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(340, 110, 131, 21))
        self.label_4.setFont(font2)
        self.RR12 = QLineEdit(self.tab_4)
        self.RR12.setObjectName(u"RR12")
        self.RR12.setGeometry(QRect(600, 90, 51, 51))
        self.RR12.setFont(font1)
        self.RR12.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR12.setReadOnly(True)
        self.RR02 = QLineEdit(self.tab_4)
        self.RR02.setObjectName(u"RR02")
        self.RR02.setGeometry(QRect(600, 30, 51, 51))
        self.RR02.setFont(font1)
        self.RR02.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RR02.setReadOnly(True)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.btnMultiplicar = QPushButton(self.tab_5)
        self.btnMultiplicar.setObjectName(u"btnMultiplicar")
        self.btnMultiplicar.setGeometry(QRect(120, 100, 141, 51))
        self.btnMultiplicar.setFont(font)
        self.btnMultiplicar.setStyleSheet(u"background-color: rgb(141, 141, 141);")
        self.RM10 = QLineEdit(self.tab_5)
        self.RM10.setObjectName(u"RM10")
        self.RM10.setGeometry(QRect(480, 90, 51, 51))
        self.RM10.setFont(font1)
        self.RM10.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM10.setReadOnly(True)
        self.RM00 = QLineEdit(self.tab_5)
        self.RM00.setObjectName(u"RM00")
        self.RM00.setGeometry(QRect(480, 30, 51, 51))
        self.RM00.setFont(font1)
        self.RM00.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM00.setReadOnly(True)
        self.RM01 = QLineEdit(self.tab_5)
        self.RM01.setObjectName(u"RM01")
        self.RM01.setGeometry(QRect(540, 30, 51, 51))
        self.RM01.setFont(font1)
        self.RM01.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM01.setReadOnly(True)
        self.RM02 = QLineEdit(self.tab_5)
        self.RM02.setObjectName(u"RM02")
        self.RM02.setGeometry(QRect(600, 30, 51, 51))
        self.RM02.setFont(font1)
        self.RM02.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM02.setReadOnly(True)
        self.RM22 = QLineEdit(self.tab_5)
        self.RM22.setObjectName(u"RM22")
        self.RM22.setGeometry(QRect(600, 150, 51, 51))
        self.RM22.setFont(font1)
        self.RM22.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM22.setReadOnly(True)
        self.RM12 = QLineEdit(self.tab_5)
        self.RM12.setObjectName(u"RM12")
        self.RM12.setGeometry(QRect(600, 90, 51, 51))
        self.RM12.setFont(font1)
        self.RM12.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM12.setReadOnly(True)
        self.RM11 = QLineEdit(self.tab_5)
        self.RM11.setObjectName(u"RM11")
        self.RM11.setGeometry(QRect(540, 90, 51, 51))
        self.RM11.setFont(font1)
        self.RM11.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM11.setReadOnly(True)
        self.RM20 = QLineEdit(self.tab_5)
        self.RM20.setObjectName(u"RM20")
        self.RM20.setGeometry(QRect(480, 150, 51, 51))
        self.RM20.setFont(font1)
        self.RM20.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM20.setReadOnly(True)
        self.label_5 = QLabel(self.tab_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(340, 110, 131, 21))
        self.label_5.setFont(font2)
        self.RM21 = QLineEdit(self.tab_5)
        self.RM21.setObjectName(u"RM21")
        self.RM21.setGeometry(QRect(540, 150, 51, 51))
        self.RM21.setFont(font1)
        self.RM21.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RM21.setReadOnly(True)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 130, 71, 21))
        self.label.setFont(font2)
        self.AA00 = QLineEdit(self.tab)
        self.AA00.setObjectName(u"AA00")
        self.AA00.setGeometry(QRect(180, 60, 51, 51))
        self.AA00.setFont(font1)
        self.AA00.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.AA00.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA10 = QLineEdit(self.tab)
        self.AA10.setObjectName(u"AA10")
        self.AA10.setGeometry(QRect(180, 120, 51, 51))
        self.AA10.setFont(font1)
        self.AA10.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA20 = QLineEdit(self.tab)
        self.AA20.setObjectName(u"AA20")
        self.AA20.setGeometry(QRect(180, 180, 51, 51))
        self.AA20.setFont(font1)
        self.AA20.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA01 = QLineEdit(self.tab)
        self.AA01.setObjectName(u"AA01")
        self.AA01.setGeometry(QRect(240, 60, 51, 51))
        self.AA01.setFont(font1)
        self.AA01.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA11 = QLineEdit(self.tab)
        self.AA11.setObjectName(u"AA11")
        self.AA11.setGeometry(QRect(240, 120, 51, 51))
        self.AA11.setFont(font1)
        self.AA11.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA21 = QLineEdit(self.tab)
        self.AA21.setObjectName(u"AA21")
        self.AA21.setGeometry(QRect(240, 180, 51, 51))
        self.AA21.setFont(font1)
        self.AA21.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA12 = QLineEdit(self.tab)
        self.AA12.setObjectName(u"AA12")
        self.AA12.setGeometry(QRect(300, 120, 51, 51))
        self.AA12.setFont(font1)
        self.AA12.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA02 = QLineEdit(self.tab)
        self.AA02.setObjectName(u"AA02")
        self.AA02.setGeometry(QRect(300, 60, 51, 51))
        self.AA02.setFont(font1)
        self.AA02.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AA22 = QLineEdit(self.tab)
        self.AA22.setObjectName(u"AA22")
        self.AA22.setGeometry(QRect(300, 180, 51, 51))
        self.AA22.setFont(font1)
        self.AA22.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(420, 130, 71, 21))
        self.label_2.setFont(font2)
        self.AB11 = QLineEdit(self.tab)
        self.AB11.setObjectName(u"AB11")
        self.AB11.setGeometry(QRect(560, 120, 51, 51))
        self.AB11.setFont(font1)
        self.AB11.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB01 = QLineEdit(self.tab)
        self.AB01.setObjectName(u"AB01")
        self.AB01.setGeometry(QRect(560, 60, 51, 51))
        self.AB01.setFont(font1)
        self.AB01.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB22 = QLineEdit(self.tab)
        self.AB22.setObjectName(u"AB22")
        self.AB22.setGeometry(QRect(620, 180, 51, 51))
        self.AB22.setFont(font1)
        self.AB22.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB00 = QLineEdit(self.tab)
        self.AB00.setObjectName(u"AB00")
        self.AB00.setGeometry(QRect(500, 60, 51, 51))
        self.AB00.setFont(font1)
        self.AB00.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB10 = QLineEdit(self.tab)
        self.AB10.setObjectName(u"AB10")
        self.AB10.setGeometry(QRect(500, 120, 51, 51))
        self.AB10.setFont(font1)
        self.AB10.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB12 = QLineEdit(self.tab)
        self.AB12.setObjectName(u"AB12")
        self.AB12.setGeometry(QRect(620, 120, 51, 51))
        self.AB12.setFont(font1)
        self.AB12.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB21 = QLineEdit(self.tab)
        self.AB21.setObjectName(u"AB21")
        self.AB21.setGeometry(QRect(560, 180, 51, 51))
        self.AB21.setFont(font1)
        self.AB21.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB20 = QLineEdit(self.tab)
        self.AB20.setObjectName(u"AB20")
        self.AB20.setGeometry(QRect(500, 180, 51, 51))
        self.AB20.setFont(font1)
        self.AB20.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AB02 = QLineEdit(self.tab)
        self.AB02.setObjectName(u"AB02")
        self.AB02.setGeometry(QRect(620, 60, 51, 51))
        self.AB02.setFont(font1)
        self.AB02.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_3 = QTabWidget(self.tab_2)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 0, 961, 571))
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.RI22 = QLineEdit(self.tab_6)
        self.RI22.setObjectName(u"RI22")
        self.RI22.setGeometry(QRect(620, 410, 51, 51))
        self.RI22.setFont(font1)
        self.RI22.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI22.setReadOnly(True)
        self.RI01 = QLineEdit(self.tab_6)
        self.RI01.setObjectName(u"RI01")
        self.RI01.setGeometry(QRect(560, 290, 51, 51))
        self.RI01.setFont(font1)
        self.RI01.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI01.setReadOnly(True)
        self.RI00 = QLineEdit(self.tab_6)
        self.RI00.setObjectName(u"RI00")
        self.RI00.setGeometry(QRect(500, 290, 51, 51))
        self.RI00.setFont(font1)
        self.RI00.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI00.setReadOnly(True)
        self.RI20 = QLineEdit(self.tab_6)
        self.RI20.setObjectName(u"RI20")
        self.RI20.setGeometry(QRect(500, 410, 51, 51))
        self.RI20.setFont(font1)
        self.RI20.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI20.setReadOnly(True)
        self.RI11 = QLineEdit(self.tab_6)
        self.RI11.setObjectName(u"RI11")
        self.RI11.setGeometry(QRect(560, 350, 51, 51))
        self.RI11.setFont(font1)
        self.RI11.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI11.setReadOnly(True)
        self.RI21 = QLineEdit(self.tab_6)
        self.RI21.setObjectName(u"RI21")
        self.RI21.setGeometry(QRect(560, 410, 51, 51))
        self.RI21.setFont(font1)
        self.RI21.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI21.setReadOnly(True)
        self.RI10 = QLineEdit(self.tab_6)
        self.RI10.setObjectName(u"RI10")
        self.RI10.setGeometry(QRect(500, 350, 51, 51))
        self.RI10.setFont(font1)
        self.RI10.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI10.setReadOnly(True)
        self.label_7 = QLabel(self.tab_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 360, 131, 21))
        self.label_7.setFont(font2)
        self.RI12 = QLineEdit(self.tab_6)
        self.RI12.setObjectName(u"RI12")
        self.RI12.setGeometry(QRect(620, 350, 51, 51))
        self.RI12.setFont(font1)
        self.RI12.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI12.setReadOnly(True)
        self.RI02 = QLineEdit(self.tab_6)
        self.RI02.setObjectName(u"RI02")
        self.RI02.setGeometry(QRect(620, 290, 51, 51))
        self.RI02.setFont(font1)
        self.RI02.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.RI02.setReadOnly(True)
        self.btnMatrizInversa = QPushButton(self.tab_6)
        self.btnMatrizInversa.setObjectName(u"btnMatrizInversa")
        self.btnMatrizInversa.setGeometry(QRect(120, 350, 151, 51))
        self.btnMatrizInversa.setFont(font)
        self.btnMatrizInversa.setStyleSheet(u"background-color: rgb(141, 141, 141);")
        self.AO02 = QLineEdit(self.tab_6)
        self.AO02.setObjectName(u"AO02")
        self.AO02.setGeometry(QRect(450, 40, 51, 51))
        self.AO02.setFont(font1)
        self.AO02.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO20 = QLineEdit(self.tab_6)
        self.AO20.setObjectName(u"AO20")
        self.AO20.setGeometry(QRect(330, 160, 51, 51))
        self.AO20.setFont(font1)
        self.AO20.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO11 = QLineEdit(self.tab_6)
        self.AO11.setObjectName(u"AO11")
        self.AO11.setGeometry(QRect(390, 100, 51, 51))
        self.AO11.setFont(font1)
        self.AO11.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO21 = QLineEdit(self.tab_6)
        self.AO21.setObjectName(u"AO21")
        self.AO21.setGeometry(QRect(390, 160, 51, 51))
        self.AO21.setFont(font1)
        self.AO21.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO12 = QLineEdit(self.tab_6)
        self.AO12.setObjectName(u"AO12")
        self.AO12.setGeometry(QRect(450, 100, 51, 51))
        self.AO12.setFont(font1)
        self.AO12.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO01 = QLineEdit(self.tab_6)
        self.AO01.setObjectName(u"AO01")
        self.AO01.setGeometry(QRect(390, 40, 51, 51))
        self.AO01.setFont(font1)
        self.AO01.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO22 = QLineEdit(self.tab_6)
        self.AO22.setObjectName(u"AO22")
        self.AO22.setGeometry(QRect(450, 160, 51, 51))
        self.AO22.setFont(font1)
        self.AO22.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO10 = QLineEdit(self.tab_6)
        self.AO10.setObjectName(u"AO10")
        self.AO10.setGeometry(QRect(330, 100, 51, 51))
        self.AO10.setFont(font1)
        self.AO10.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.AO00 = QLineEdit(self.tab_6)
        self.AO00.setObjectName(u"AO00")
        self.AO00.setGeometry(QRect(330, 40, 51, 51))
        self.AO00.setFont(font1)
        self.AO00.setStyleSheet(u"background-color: rgb(108, 108, 108);")
        self.label_6 = QLabel(self.tab_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(240, 120, 71, 21))
        self.label_6.setFont(font2)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_8 = QLabel(self.tab_7)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(260, 50, 41, 31))
        font3 = QFont()
        font3.setPointSize(18)
        font3.setBold(True)
        self.label_8.setFont(font3)
        self.XEQ1 = QLineEdit(self.tab_7)
        self.XEQ1.setObjectName(u"XEQ1")
        self.XEQ1.setGeometry(QRect(200, 50, 51, 41))
        self.YEQ1 = QLineEdit(self.tab_7)
        self.YEQ1.setObjectName(u"YEQ1")
        self.YEQ1.setGeometry(QRect(310, 50, 51, 41))
        self.label_9 = QLabel(self.tab_7)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(370, 50, 41, 31))
        self.label_9.setFont(font3)
        self.label_10 = QLabel(self.tab_7)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(480, 50, 41, 31))
        self.label_10.setFont(font3)
        self.ZEQ1 = QLineEdit(self.tab_7)
        self.ZEQ1.setObjectName(u"ZEQ1")
        self.ZEQ1.setGeometry(QRect(420, 50, 51, 41))
        self.IEQ1 = QLineEdit(self.tab_7)
        self.IEQ1.setObjectName(u"IEQ1")
        self.IEQ1.setGeometry(QRect(530, 50, 51, 41))
        self.ZEQ2 = QLineEdit(self.tab_7)
        self.ZEQ2.setObjectName(u"ZEQ2")
        self.ZEQ2.setGeometry(QRect(420, 110, 51, 41))
        self.label_11 = QLabel(self.tab_7)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(370, 110, 41, 31))
        self.label_11.setFont(font3)
        self.IEQ2 = QLineEdit(self.tab_7)
        self.IEQ2.setObjectName(u"IEQ2")
        self.IEQ2.setGeometry(QRect(530, 110, 51, 41))
        self.YEQ2 = QLineEdit(self.tab_7)
        self.YEQ2.setObjectName(u"YEQ2")
        self.YEQ2.setGeometry(QRect(310, 110, 51, 41))
        self.XEQ2 = QLineEdit(self.tab_7)
        self.XEQ2.setObjectName(u"XEQ2")
        self.XEQ2.setGeometry(QRect(200, 110, 51, 41))
        self.label_12 = QLabel(self.tab_7)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(260, 110, 41, 31))
        self.label_12.setFont(font3)
        self.label_13 = QLabel(self.tab_7)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(480, 110, 41, 31))
        self.label_13.setFont(font3)
        self.XEQ3 = QLineEdit(self.tab_7)
        self.XEQ3.setObjectName(u"XEQ3")
        self.XEQ3.setGeometry(QRect(200, 170, 51, 41))
        self.YEQ3 = QLineEdit(self.tab_7)
        self.YEQ3.setObjectName(u"YEQ3")
        self.YEQ3.setGeometry(QRect(310, 170, 51, 41))
        self.ZEQ3 = QLineEdit(self.tab_7)
        self.ZEQ3.setObjectName(u"ZEQ3")
        self.ZEQ3.setGeometry(QRect(420, 170, 51, 41))
        self.label_14 = QLabel(self.tab_7)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(260, 170, 41, 31))
        self.label_14.setFont(font3)
        self.IEQ3 = QLineEdit(self.tab_7)
        self.IEQ3.setObjectName(u"IEQ3")
        self.IEQ3.setGeometry(QRect(530, 170, 51, 41))
        self.label_15 = QLabel(self.tab_7)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(370, 170, 41, 31))
        self.label_15.setFont(font3)
        self.label_16 = QLabel(self.tab_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(480, 170, 41, 31))
        self.label_16.setFont(font3)
        self.btnSistemaDeEcuaciones = QPushButton(self.tab_7)
        self.btnSistemaDeEcuaciones.setObjectName(u"btnSistemaDeEcuaciones")
        self.btnSistemaDeEcuaciones.setGeometry(QRect(180, 350, 211, 51))
        self.btnSistemaDeEcuaciones.setFont(font)
        self.btnSistemaDeEcuaciones.setStyleSheet(u"background-color: rgb(141, 141, 141);")
        self.lblX = QLabel(self.tab_7)
        self.lblX.setObjectName(u"lblX")
        self.lblX.setGeometry(QRect(450, 300, 351, 41))
        font4 = QFont()
        font4.setPointSize(20)
        font4.setBold(True)
        self.lblX.setFont(font4)
        self.lblY = QLabel(self.tab_7)
        self.lblY.setObjectName(u"lblY")
        self.lblY.setGeometry(QRect(450, 350, 351, 41))
        self.lblY.setFont(font4)
        self.lblZ = QLabel(self.tab_7)
        self.lblZ.setObjectName(u"lblZ")
        self.lblZ.setGeometry(QRect(450, 400, 351, 41))
        self.lblZ.setFont(font4)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.btnSuma.setText(QCoreApplication.translate("MainWindow", u"Sumar matrices", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Suma", None))
        self.btnResta.setText(QCoreApplication.translate("MainWindow", u"Restar matrices", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Resta", None))
        self.btnMultiplicar.setText(QCoreApplication.translate("MainWindow", u"Multiplicar matrices", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Multiplicaci\u00f3n", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Matriz A:", None))
        self.AA00.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Matriz B:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Aritm\u00e9tica", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.btnMatrizInversa.setText(QCoreApplication.translate("MainWindow", u"Calcular matriz inversa", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Matriz A:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Matriz inversa", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"x + ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"y + ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"z =", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"y + ", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"x + ", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"z =", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"x + ", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"y + ", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"z =", None))
        self.btnSistemaDeEcuaciones.setText(QCoreApplication.translate("MainWindow", u"Calcular Sistema de Ecuaciones", None))
        self.lblX.setText(QCoreApplication.translate("MainWindow", u"x =", None))
        self.lblY.setText(QCoreApplication.translate("MainWindow", u"y =", None))
        self.lblZ.setText(QCoreApplication.translate("MainWindow", u"z =", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Sistema de ecuaciones lineales", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Operaciones con matrices", None))
    # retranslateUi