# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Diseño Parcial II - Métodos NuméricospbHbxG.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(974, 656)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 971, 601))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 270, 961, 301))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.RS22 = QLineEdit(self.tab_3)
        self.RS22.setObjectName(u"RS22")
        self.RS22.setGeometry(QRect(640, 150, 31, 31))
        self.RS01 = QLineEdit(self.tab_3)
        self.RS01.setObjectName(u"RS01")
        self.RS01.setGeometry(QRect(600, 50, 31, 31))
        self.RS00 = QLineEdit(self.tab_3)
        self.RS00.setObjectName(u"RS00")
        self.RS00.setGeometry(QRect(560, 50, 31, 31))
        self.RS20 = QLineEdit(self.tab_3)
        self.RS20.setObjectName(u"RS20")
        self.RS20.setGeometry(QRect(560, 150, 31, 31))
        self.RS11 = QLineEdit(self.tab_3)
        self.RS11.setObjectName(u"RS11")
        self.RS11.setGeometry(QRect(600, 100, 31, 31))
        self.RS21 = QLineEdit(self.tab_3)
        self.RS21.setObjectName(u"RS21")
        self.RS21.setGeometry(QRect(600, 150, 31, 31))
        self.RS10 = QLineEdit(self.tab_3)
        self.RS10.setObjectName(u"RS10")
        self.RS10.setGeometry(QRect(560, 100, 31, 31))
        self.label_3 = QLabel(self.tab_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(460, 110, 91, 21))
        self.RS12 = QLineEdit(self.tab_3)
        self.RS12.setObjectName(u"RS12")
        self.RS12.setGeometry(QRect(640, 100, 31, 31))
        self.RS02 = QLineEdit(self.tab_3)
        self.RS02.setObjectName(u"RS02")
        self.RS02.setGeometry(QRect(640, 50, 31, 31))
        self.btnSuma = QPushButton(self.tab_3)
        self.btnSuma.setObjectName(u"btnSuma")
        self.btnSuma.setGeometry(QRect(220, 100, 131, 41))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.RR01 = QLineEdit(self.tab_4)
        self.RR01.setObjectName(u"RR01")
        self.RR01.setGeometry(QRect(600, 50, 31, 31))
        self.RR00 = QLineEdit(self.tab_4)
        self.RR00.setObjectName(u"RR00")
        self.RR00.setGeometry(QRect(560, 50, 31, 31))
        self.RR22 = QLineEdit(self.tab_4)
        self.RR22.setObjectName(u"RR22")
        self.RR22.setGeometry(QRect(640, 150, 31, 31))
        self.RR20 = QLineEdit(self.tab_4)
        self.RR20.setObjectName(u"RR20")
        self.RR20.setGeometry(QRect(560, 150, 31, 31))
        self.RR11 = QLineEdit(self.tab_4)
        self.RR11.setObjectName(u"RR11")
        self.RR11.setGeometry(QRect(600, 100, 31, 31))
        self.RR21 = QLineEdit(self.tab_4)
        self.RR21.setObjectName(u"RR21")
        self.RR21.setGeometry(QRect(600, 150, 31, 31))
        self.RR10 = QLineEdit(self.tab_4)
        self.RR10.setObjectName(u"RR10")
        self.RR10.setGeometry(QRect(560, 100, 31, 31))
        self.btnResta = QPushButton(self.tab_4)
        self.btnResta.setObjectName(u"btnResta")
        self.btnResta.setGeometry(QRect(220, 100, 131, 41))
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(460, 110, 91, 21))
        self.RR12 = QLineEdit(self.tab_4)
        self.RR12.setObjectName(u"RR12")
        self.RR12.setGeometry(QRect(640, 100, 31, 31))
        self.RR02 = QLineEdit(self.tab_4)
        self.RR02.setObjectName(u"RR02")
        self.RR02.setGeometry(QRect(640, 50, 31, 31))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.btnMultiplicar = QPushButton(self.tab_5)
        self.btnMultiplicar.setObjectName(u"btnMultiplicar")
        self.btnMultiplicar.setGeometry(QRect(220, 100, 131, 41))
        self.RM10 = QLineEdit(self.tab_5)
        self.RM10.setObjectName(u"RM10")
        self.RM10.setGeometry(QRect(560, 100, 31, 31))
        self.RM00 = QLineEdit(self.tab_5)
        self.RM00.setObjectName(u"RM00")
        self.RM00.setGeometry(QRect(560, 50, 31, 31))
        self.RM01 = QLineEdit(self.tab_5)
        self.RM01.setObjectName(u"RM01")
        self.RM01.setGeometry(QRect(600, 50, 31, 31))
        self.RM02 = QLineEdit(self.tab_5)
        self.RM02.setObjectName(u"RM02")
        self.RM02.setGeometry(QRect(640, 50, 31, 31))
        self.RM22 = QLineEdit(self.tab_5)
        self.RM22.setObjectName(u"RM22")
        self.RM22.setGeometry(QRect(640, 150, 31, 31))
        self.RM12 = QLineEdit(self.tab_5)
        self.RM12.setObjectName(u"RM12")
        self.RM12.setGeometry(QRect(640, 100, 31, 31))
        self.RM11 = QLineEdit(self.tab_5)
        self.RM11.setObjectName(u"RM11")
        self.RM11.setGeometry(QRect(600, 100, 31, 31))
        self.RM20 = QLineEdit(self.tab_5)
        self.RM20.setObjectName(u"RM20")
        self.RM20.setGeometry(QRect(560, 150, 31, 31))
        self.label_5 = QLabel(self.tab_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(460, 110, 91, 21))
        self.RM21 = QLineEdit(self.tab_5)
        self.RM21.setObjectName(u"RM21")
        self.RM21.setGeometry(QRect(600, 150, 31, 31))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 120, 71, 21))
        self.AA00 = QLineEdit(self.tab)
        self.AA00.setObjectName(u"AA00")
        self.AA00.setGeometry(QRect(300, 60, 31, 31))
        self.AA10 = QLineEdit(self.tab)
        self.AA10.setObjectName(u"AA10")
        self.AA10.setGeometry(QRect(300, 110, 31, 31))
        self.AA20 = QLineEdit(self.tab)
        self.AA20.setObjectName(u"AA20")
        self.AA20.setGeometry(QRect(300, 160, 31, 31))
        self.AA01 = QLineEdit(self.tab)
        self.AA01.setObjectName(u"AA01")
        self.AA01.setGeometry(QRect(340, 60, 31, 31))
        self.AA11 = QLineEdit(self.tab)
        self.AA11.setObjectName(u"AA11")
        self.AA11.setGeometry(QRect(340, 110, 31, 31))
        self.AA21 = QLineEdit(self.tab)
        self.AA21.setObjectName(u"AA21")
        self.AA21.setGeometry(QRect(340, 160, 31, 31))
        self.AA12 = QLineEdit(self.tab)
        self.AA12.setObjectName(u"AA12")
        self.AA12.setGeometry(QRect(380, 110, 31, 31))
        self.AA02 = QLineEdit(self.tab)
        self.AA02.setObjectName(u"AA02")
        self.AA02.setGeometry(QRect(380, 60, 31, 31))
        self.AA22 = QLineEdit(self.tab)
        self.AA22.setObjectName(u"AA22")
        self.AA22.setGeometry(QRect(380, 160, 31, 31))
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(480, 120, 71, 21))
        self.AB11 = QLineEdit(self.tab)
        self.AB11.setObjectName(u"AB11")
        self.AB11.setGeometry(QRect(600, 110, 31, 31))
        self.AB01 = QLineEdit(self.tab)
        self.AB01.setObjectName(u"AB01")
        self.AB01.setGeometry(QRect(600, 60, 31, 31))
        self.AB22 = QLineEdit(self.tab)
        self.AB22.setObjectName(u"AB22")
        self.AB22.setGeometry(QRect(640, 160, 31, 31))
        self.AB00 = QLineEdit(self.tab)
        self.AB00.setObjectName(u"AB00")
        self.AB00.setGeometry(QRect(560, 60, 31, 31))
        self.AB10 = QLineEdit(self.tab)
        self.AB10.setObjectName(u"AB10")
        self.AB10.setGeometry(QRect(560, 110, 31, 31))
        self.AB12 = QLineEdit(self.tab)
        self.AB12.setObjectName(u"AB12")
        self.AB12.setGeometry(QRect(640, 110, 31, 31))
        self.AB21 = QLineEdit(self.tab)
        self.AB21.setObjectName(u"AB21")
        self.AB21.setGeometry(QRect(600, 160, 31, 31))
        self.AB20 = QLineEdit(self.tab)
        self.AB20.setObjectName(u"AB20")
        self.AB20.setGeometry(QRect(560, 160, 31, 31))
        self.AB02 = QLineEdit(self.tab)
        self.AB02.setObjectName(u"AB02")
        self.AB02.setGeometry(QRect(640, 60, 31, 31))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(320, 110, 71, 21))
        self.AO11 = QLineEdit(self.tab_2)
        self.AO11.setObjectName(u"AO11")
        self.AO11.setGeometry(QRect(440, 100, 31, 31))
        self.AO01 = QLineEdit(self.tab_2)
        self.AO01.setObjectName(u"AO01")
        self.AO01.setGeometry(QRect(440, 50, 31, 31))
        self.AO22 = QLineEdit(self.tab_2)
        self.AO22.setObjectName(u"AO22")
        self.AO22.setGeometry(QRect(480, 150, 31, 31))
        self.AO00 = QLineEdit(self.tab_2)
        self.AO00.setObjectName(u"AO00")
        self.AO00.setGeometry(QRect(400, 50, 31, 31))
        self.AO10 = QLineEdit(self.tab_2)
        self.AO10.setObjectName(u"AO10")
        self.AO10.setGeometry(QRect(400, 100, 31, 31))
        self.AO12 = QLineEdit(self.tab_2)
        self.AO12.setObjectName(u"AO12")
        self.AO12.setGeometry(QRect(480, 100, 31, 31))
        self.AO21 = QLineEdit(self.tab_2)
        self.AO21.setObjectName(u"AO21")
        self.AO21.setGeometry(QRect(440, 150, 31, 31))
        self.AO20 = QLineEdit(self.tab_2)
        self.AO20.setObjectName(u"AO20")
        self.AO20.setGeometry(QRect(400, 150, 31, 31))
        self.AO02 = QLineEdit(self.tab_2)
        self.AO02.setObjectName(u"AO02")
        self.AO02.setGeometry(QRect(480, 50, 31, 31))
        self.tabWidget_3 = QTabWidget(self.tab_2)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 270, 961, 301))
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.RI22 = QLineEdit(self.tab_6)
        self.RI22.setObjectName(u"RI22")
        self.RI22.setGeometry(QRect(640, 150, 31, 31))
        self.RI01 = QLineEdit(self.tab_6)
        self.RI01.setObjectName(u"RI01")
        self.RI01.setGeometry(QRect(600, 50, 31, 31))
        self.RI00 = QLineEdit(self.tab_6)
        self.RI00.setObjectName(u"RI00")
        self.RI00.setGeometry(QRect(560, 50, 31, 31))
        self.RI20 = QLineEdit(self.tab_6)
        self.RI20.setObjectName(u"RI20")
        self.RI20.setGeometry(QRect(560, 150, 31, 31))
        self.RI11 = QLineEdit(self.tab_6)
        self.RI11.setObjectName(u"RI11")
        self.RI11.setGeometry(QRect(600, 100, 31, 31))
        self.RI21 = QLineEdit(self.tab_6)
        self.RI21.setObjectName(u"RI21")
        self.RI21.setGeometry(QRect(600, 150, 31, 31))
        self.RI10 = QLineEdit(self.tab_6)
        self.RI10.setObjectName(u"RI10")
        self.RI10.setGeometry(QRect(560, 100, 31, 31))
        self.label_7 = QLabel(self.tab_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(460, 110, 91, 21))
        self.RI12 = QLineEdit(self.tab_6)
        self.RI12.setObjectName(u"RI12")
        self.RI12.setGeometry(QRect(640, 100, 31, 31))
        self.RI02 = QLineEdit(self.tab_6)
        self.RI02.setObjectName(u"RI02")
        self.RI02.setGeometry(QRect(640, 50, 31, 31))
        self.btnMatrizInversa = QPushButton(self.tab_6)
        self.btnMatrizInversa.setObjectName(u"btnMatrizInversa")
        self.btnMatrizInversa.setGeometry(QRect(220, 100, 131, 41))
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 974, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.btnSuma.setText(QCoreApplication.translate("MainWindow", u"Sumar matrices", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Suma", None))
        self.btnResta.setText(QCoreApplication.translate("MainWindow", u"Restar matrices", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Resta", None))
        self.btnMultiplicar.setText(QCoreApplication.translate("MainWindow", u"Multiplicar matrices", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Multiplicaci\u00f3n", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Matriz A:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Matriz B:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Aritm\u00e9tica", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Matriz A:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Matriz resultante:", None))
        self.btnMatrizInversa.setText(QCoreApplication.translate("MainWindow", u"Calcular matriz inversa", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Matriz inversa", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Otros", None))
    # retranslateUi

